### ISSUE TITLE
Lenovo 100s Orca

### ISSUE THREAD

**Issue by mcmar** [GalliumOS/galliumos-baytrail#1]
The installation instructions incorrectly state that John Lewis's BOOT_STUB firmware no longer supports the 100s.
https://wiki.galliumos.org/Installing/Baytrail
It looks like that's out of date. His firmware was updated a few days ago and I successfully flashed it without bricking my device.
https://johnlewis.ie/Chromebook-ROMs/shellballs/orco/

I ran into issues when installing Gallium however. Gallium successfully booted from my usb drive. When using the installer, I encountered this error:
![image](https://cloud.githubusercontent.com/assets/8251430/14584525/f0049dc4-03fe-11e6-8d5c-6f668b3e46d9.png)

Retrying did nothing. I ignored it and pressed on. I encountered the same error once more:
![image](https://cloud.githubusercontent.com/assets/8251430/14584527/09442a3e-03ff-11e6-9841-1bb31a7afe0b.png)

I ignored it again and successfully completed the installer. I rebooted and it failed to find any bootable device:
![image](https://cloud.githubusercontent.com/assets/8251430/14584529/30442bf2-03ff-11e6-8adf-abdd8644e7d2.png)

I could still use the usb drive to boot however and doing so allowed me to inspect the ssd using gparted:
![image](https://cloud.githubusercontent.com/assets/8251430/14584535/bf2370d0-03ff-11e6-8391-6b44a4e3a8f9.png)

I also inspected it using the install tool's partition editor, which confirmed that GalliumOS had been installed to /dev/mmcblk0p1, but was simply not bootable:
![image](https://cloud.githubusercontent.com/assets/8251430/14584539/f2dbf366-03ff-11e6-9af0-d23978d09dd4.png)

If it helps, the full output of running `fdisk -l` is here: http://pastebin.com/6MiQBYba
The relevant portion is excerpted here: http://pastebin.com/75H7GutJ

I've retried this about 5 times, once with configuring the partition tables manually and another time with LVM. Every time has had the same issues during installation and the same result.

This seems to be a simple issue. Gallium is being installed correctly, however the drive is not bootable. I've seen a few other people complain of similar things. The most related would seem to be this: https://www.reddit.com/r/linux/comments/4e5dav/ubuntu_doesnt_boot_error/
It looks like Ubuntu has had issues quite recently with eMMC.
Please let me know if there's anything else I can help with for triaging and hopefully resolving this issue. Thank you.
If you happen to be in the Bay Area, I can also let you borrow the device.

**Comment by reynhout** [comment]
This is very very likely to be a bad write of the GalliumOS image to your USB drive. It happens *a lot*. :)

See the troubleshooting steps here for the usual culprits, in order of likelihood: https://wiki.galliumos.org/Installing/Creating_Bootable_USB#Troubleshooting

Thanks for the update on the JL firmware, I'll look into it and update the wiki.

After we confirm or otherwise resolve this issue, I'll disable the Issues tab for this repo. We try to keep all issue reports in a central tracking repo: https://github.com/GalliumOS/galliumos-distro/issues

Thanks again.

**Comment by reynhout** [comment]
PS: You're right, we have definitely seen issues with eMMC devices. I am not sure why the installer is trying to write to the RPMB at all, in fact.

However, we also definitely have hundreds of successful installs onto eMMC storage, and reports of success on ORCO too. The bad write/bad USB problem often manifests as IO errors during the installation. Yours looks to be a little more subtle, but I hope it turns out to be just another one of the weird ways this same problem shows itself.

**Comment by mcmar** [comment]
I verified the checksum prior to burning it. I used the Win32DiskImager tool to do it. I just tried again using a different usb drive and had the same result. I'll try verifying the contents of the usb by comparing it to the iso and I'll also try using dd to copy it on my mac and see if I get a different result

**Comment by reynhout** [comment]
It sounds like you've tested enough then. If the MD5 checks out, and you've written to two different devices, it's probably not the same problem. Still, it's worth a try with `dd`, it's quick and reliable.

**Comment by mcmar** [comment]
I verified that the usb drive was imaged correctly using:
`sudo cmp -n $(stat -f '%z' ~/galliumos-baytrail-1.0.iso) ~/galliumos-baytrail-1.0.iso /dev/disk2`

Then just for fun, I used dd to copy it and tried again with the same result.

**Comment by mcmar** [comment]
Let me know if there's anything else I can provide. I could try to gather data on what the drive looks like after the install? Or if you happen to be in the Bay Area, I could let you borrow the laptop?

**Comment by reynhout** [comment]
Hmm, well I know that some people have successfully installed on ORCO... A quick look through the Reddit traffic suggests that they might all be using RW_LEGACY from MattDevo...and also that some of them have lingering audio issues.

Unfortunately, we don't have an ORCO test device, and none of us are in SFBA (former resident here, and I miss it sometimes, so say hi for me :).

You might give Matt's RW_LEGACY a spin. You'd need to flash back to stock first, then flash RW_LEGACY only. I'm really just guessing here...you might be able to get some better info from Reddit.

**Comment by mcmar** [comment]
I found somebody on Reddit who says the 100s works with RW_LEGACY. He tried then replacing it with BOOT_STUB and had the exact same issues I've been having where it would boot from usb, but not from disk after the installation completed.
https://www.reddit.com/r/GalliumOS/comments/4dr759/galliumos_on_lenovo_100s_no_sound_through/d20leb0

**Comment by reynhout** [comment]
So it does sound firmware-related, then... If you're able to test, please keep us updated.

**Comment by reynhout** [comment]
Issue opened anew at https://github.com/GalliumOS/galliumos-distro/issues/222. This issue tracker will be disabled.
